controllers: # PID controller params for simulation (currently for gazebo)
  pid:
    left:
      speed: # Speed control PID parameters
        ramp_limit: 50.0
        kp: 85.0
        ki: 0.0
        kd: 2500.0
      torque: # Torque control PID parameters
        ramp_limit: 1000.0
        kp: 10.0
        ki: 2.0
        kd: 0.0

    right:
      speed: # Speed control PID parameters
        ramp_limit: 50.0
        kp: 85.0
        ki: 0.0
        kd: 2500.0
      torque: # Torque control PID parameters
        ramp_limit: 1000.0
        kp: 10.0
        ki: 2.0
        kd: 0.0


# keeping temporarily
  # left_speed_control:
  #   ramp_limit: 50.0
  #   kp: 3.0
  #   ki: 2.0
  #   kd: 0.0
  
  # right_speed_control:
  #   ramp_limit: 50.0
  #   kp: 3.0
  #   ki: 2.0
  #   kd: 0.0
  
  # left_torque_control:
  #   ramp_limit: 1000.0
  #   kp: 10.0
  #   ki: 2.0
  #   kd: 0.0

  # right_torque_control:
  #   ramp_limit: 1000.0
  #   kp: 10.0
  #   ki: 2.0
  #   kd: 0.0

  # speed: # Speed control PID parameters
  #   left:
  #     ramp_limit: 50.0
  #     kp: 3.0
  #     ki: 2.0
  #     kd: 0.0
  #   right:
  #     ramp_limit: 50.0
  #     kp: 3.0
  #     ki: 2.0
  #     kd: 0.0
  
  # torque: # Torque control PID parameters
  #   left:
  #     ramp_limit: 1000.0
  #     kp: 10.0
  #     ki: 2.0
  #     kd: 0.0
  #   right:
  #     ramp_limit: 1000.0
  #     kp: 10.0
  #     ki: 2.0
  #     kd: 0.0